/*
Navicat MySQL Data Transfer

Source Server         : 172.30.103.83(excrawler)
Source Server Version : 50718
Source Host           : 172.30.103.83:3306
Source Database       : excra_meta

Target Server Type    : MYSQL
Target Server Version : 50718
File Encoding         : 65001

Date: 2017-07-13 15:21:16
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for ex_crawler_platform_extract_path
-- ----------------------------
DROP TABLE IF EXISTS `ex_crawler_platform_extract_path`;
CREATE TABLE `ex_crawler_platform_extract_path` (
  `name` varchar(45) NOT NULL COMMENT 'name 为一类 可以对应多个',
  `siteCode` varchar(20) NOT NULL COMMENT '网站code',
  `ranking` int(11) NOT NULL DEFAULT '1' COMMENT '排名',
  `path` varchar(300) NOT NULL COMMENT ' 1.普通抽取对应抽取元素的路径\n 2.表格抽取对应抽取表格的路径\n3.json抽取对应json的路径\n4.正则抽取对应正则的表达式路径',
  `tableHeadPath` varchar(300) DEFAULT NULL COMMENT '表格多条数据类型 列名path',
  `tableDataPath` varchar(300) DEFAULT NULL COMMENT '表格多条数据类型 数据path',
  `filterPath` varchar(45) DEFAULT NULL COMMENT '需要过滤的 path',
  `extractAttName` varchar(45) NOT NULL COMMENT '获取值得 属性名字',
  `substringStart` varchar(45) DEFAULT NULL,
  `substringEnd` varchar(45) DEFAULT NULL,
  `appendHead` varchar(45) DEFAULT NULL COMMENT '头部追加字符',
  `appendEnd` varchar(45) DEFAULT NULL COMMENT '尾部追加字符',
  `compareAttName` varchar(45) DEFAULT NULL COMMENT '比较 的att name',
  `containKeyWord` varchar(45) DEFAULT NULL COMMENT '包含某个 字词',
  `replaceWord` varchar(45) DEFAULT NULL COMMENT '需要替换的字词',
  `replaceValue` varchar(45) DEFAULT NULL COMMENT '替换的值',
  `extractEmptyCount` int(11) NOT NULL DEFAULT '0' COMMENT '抽取结果为空的次数',
  `describe` varchar(20) DEFAULT NULL COMMENT '规则描述',
  `version` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`name`,`siteCode`,`ranking`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of ex_crawler_platform_extract_path
-- ----------------------------
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('address', 'dldc_gx', '1', 'zl', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '地址', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('address', 'dldc_ls', '1', 'zl', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '地址', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('address', 'qichacha', '1', 'ul[class=company-base]>li', null, null, null, 'text', null, null, '', '', 'text', '企业地址', '企业地址：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('address', 'tmsf', '1', 'div[class=buildtxtbox classones fl famwei]>div>div>p:contains(楼盘地址)', null, null, 'empty', 'text', null, null, '', '', '', '', '楼盘地址：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('address', 'zqfgzx', '1', 'table[class=\'table Roomcount table-bordered table-condensed table-hover\']>tbody>tr>td:eq(3)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '坐落位置', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('address_1', 'tmsf', '1', 'div[class=xf_box_02]>p:contains(售楼处地址)', null, null, null, 'text', null, null, '', '', '', '', '售楼处地址：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('apportionedArea', 'dldc_gx', '1', 'ftmj', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '分摊面积', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('apportionedArea', 'dldc_ls', '1', 'ftmj', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '分摊面积', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('area', 'zqfgzx', '1', 'table[class=\'table table-bordered table-condensed table-hover\']>tbody>tr>td:eq(3)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '面积', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('avgPrice', 'dldc_gx', '1', 'ckjg', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '销售均价', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('avgPrice', 'dldc_ls', '1', 'ckjg', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '销售均价', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('beSoldAvgPrice', 'zqfgzx', '1', 'table[class=\'table Roomcount table-bordered\']>tbody>tr:eq(0)>td:eq(6)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '拟售均价', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('bookedCount', 'zqfgzx', '1', 'table[class=\'table Roomcount table-bordered\']>tbody>tr:eq(0)>td:eq(2)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '已预订套数', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('brandName', 'tmsf', '1', 'div[class=lpxqtop]>div>div>span[class=extension famwei ft14 mgr10]>ul>li:eq(1)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('buildArea', 'dldc_gx', '1', 'jzmj', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '建筑面积', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('buildArea', 'dldc_ls', '1', 'jzmj', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '建筑面积', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('buildArea', 'tmsf', '1', 'div[class=buildshowin_contant ft14 colordg]>ul>li:contains(总建筑面积)', null, null, 'empty', 'text', null, null, '', '', '', '', '总建筑面积：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('buildArea_1', 'tmsf', '1', 'div[id=myCont5]>div:eq(6)>p:contains(建筑面积)>span:eq(1)', null, null, null, 'text', null, null, '', '', '', '', '总建筑面积：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('buildName', 'zqfgzx', '1', 'table[class=\'table Roomcount table-bordered table-condensed table-hover\']>tbody>tr>td:eq(0)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '栋名称', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('buildStyle', 'tmsf', '1', 'div[class=buildtxtbox classones fl famwei]>ul>li:contains(建筑形式)', null, null, 'empty', 'text', null, null, '', '', '', '', '建筑形式：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('buildStyle_1', 'tmsf', '1', 'div[class=xf_box_02]>p:contains(建筑形式)', null, null, null, 'text', '建筑形式：', '装修状况', '', '', '', '', null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('businessType', 'cqfcglj', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, null, null, 'text', '业务类型', '业务类型', null, '0', '业务类型', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('businessType', 'cqgtfw', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, '', '', 'text', '业务类型', '业务类型', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('canSoldCount', 'zqfgzx', '1', 'table[class=\'table Roomcount table-bordered\']>tbody>tr:eq(0)>td:eq(1)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '可售套数', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('capacityRate', 'tmsf', '1', 'div[class=buildshowin_contant ft14 colordg]>ul>li:contains(容 积 率)', null, null, 'empty', 'text', null, null, '', '', '', '', '容 积 率：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('capacityRate_1', 'tmsf', '1', 'div[id=myCont5]>div:eq(6)>p:contains(容 积 率)', null, null, null, 'text', null, null, '', '', '', '', '容 积 率：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('company', 'qichacha', '1', 'span[class=clear m_comInfo]>span>span:eq(0)', null, null, null, 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('companyName', 'cqfcglj', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, null, null, 'text', '售房单位名称', '售房单位名称', null, '0', '售房单位名称', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('companyName', 'cqgtfw', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, '', '', 'text', '售房单位名称', '售房单位名称', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('completeUnitName', 'zqfgzx', '1', 'table[class=\'table table-bordered table-condensed table-hover\']>tbody>tr>td:eq(0)>a', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '楼盘名称', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('corporater', 'qichacha', '1', 'ul[class=company-base]>li', null, null, null, 'text', null, null, '', '', 'text', '法定代表', '法定代表：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('corporater', 'qichacha', '2', 'ul[class=company-base]>li', null, null, 'empty', 'text', null, null, '', '', 'text', '法定代表人', '法定代表人：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('coversArea', 'tmsf', '1', 'div[class=buildshowin_contant ft14 colordg]>ul>li:contains(占地面积)', null, null, 'empty', 'text', null, null, '', '', '', '', '占地面积：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('coversArea_1', 'tmsf', '1', 'div[id=myCont5]>div:eq(6)>p:contains(占地面积)', null, null, null, 'text', null, null, '', '', '', '', '占地面积：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('dataUrl', 'cqfcglj', '1', 'table[class=table1 table2]>tbody>tr>td>a', null, null, 'empty', 'href', null, null, null, null, '', null, null, null, '0', '抽取重庆房产管理局商品房预售许可 内容页', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('dataUrl', 'qichacha', '1', 'div[class=col-md-12]>section>a', null, null, null, 'href', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('dealAvgPrice', 'zqfgzx', '1', 'table[class=\'table Roomcount table-bordered\']>tbody>tr:eq(0)>td:eq(5)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '成交均价', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('developer', 'dldc_gx', '1', 'kfsmc', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '开发商', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('developer', 'dldc_ls', '1', 'kfsmc', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '开发商', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('developer', 'zqfgzx', '1', 'table[class=\'table Roomcount table-bordered table-condensed table-hover\']>tbody>tr>td:eq(4)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '开发商', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('developerName', 'nb_cnnbfdc', '1', 'table>tbody>tr:gt(0)>td:eq(3)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('district', 'dldc_gx', '1', 'xzq', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '行政区', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('district', 'dldc_ls', '1', 'xzq', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '行政区', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('district', 'nb_cnnbfdc', '1', 'td[class=sp_sck]>table>tbody>tr>td[class=sp_line]:eq(2)>span[class=sp_f12]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('district', 'tmsf', '1', 'div[class=website colormg]>a[id=districtname]', null, null, 'empty', 'text', null, null, '', '', '', '', '楼盘', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('district_1', 'tmsf', '1', 'div[class=xf_box_02]>p:contains(所属城区)', null, null, null, 'text', null, null, '', '', '', '', '所属城区：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('filedCount', 'zqfgzx', '1', 'table[class=\'table Roomcount table-bordered\']>tbody>tr:eq(0)>td:eq(3)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '备案套数', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('foundDate', 'qichacha', '1', 'ul[class=company-base]>li', null, null, null, 'text', null, null, '', '', 'text', '成立日期', '成立日期：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('greeningRate', 'tmsf', '1', 'div[class=buildshowin_contant ft14 colordg]>ul>li:contains(绿 化 率)', null, null, 'empty', 'text', null, null, '', '', '', '', '绿 化 率：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('greeningRate_1', 'tmsf', '1', 'div[id=myCont5]>div:eq(6)>p:contains(绿 化 率)', null, null, null, 'text', null, null, '', '', '', '', '绿 化 率：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('groundLayer', 'dldc_gx', '1', 'dscs', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '地上层数', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('groundLayer', 'dldc_ls', '1', 'dscs', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '地上层数', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('houseAddress', 'cqfcglj', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, null, null, 'text', '房屋坐落', '房屋坐落', null, '0', '房屋坐落', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('houseAddress', 'cqgtfw', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, '', '', 'text', '房屋坐落', '房屋坐落', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('houseFloor', 'tmsf', '1', 'div[class=buildoneinfo]>ul>li:contains(所在层数：)', null, null, null, 'text', null, null, '', '', '', '', '所在层数：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('houseFloor', 'tmsf', '2', 'div[class=zst]>table>tbody>tr:contains(所在层数)>td:contains(层):eq(1)', null, null, null, 'text', null, null, '', '', '', '', null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('houseUrl', 'tmsf', '1', 'div[id=buildnavbar]>a:contains(销控表)', null, null, 'empty', 'href', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('issueDate', 'cqfcglj', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, null, null, 'text', '发证日期', '发证日期', null, '0', '发证日期', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('issueDate', 'cqgtfw', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, '', '', 'text', '发证日期', '发证日期', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('issueDate', 'dldc_gx', '1', 'fzrq', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '发证日期', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('issueDate', 'dldc_ls', '1', 'fzrq', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '发证日期', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('issueDate', 'qichacha', '1', 'ul[class=company-base]>li', null, null, null, 'text', null, null, '', '', 'text', '发照日期', '发照日期：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('issuingAuthority', 'dldc_gx', '1', 'fzjg', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '发证机关', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('issuingAuthority', 'dldc_ls', '1', 'fzjg', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '发证机关', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('latitude', 'tmsf', '1', 'div[id=container]', null, null, 'empty', '', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('longitude', 'tmsf', '1', 'div[id=container]', null, null, 'empty', '', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('nextUrl', 'cqfcglj', '1', 'div[class=page]>a', null, null, 'empty', 'href', null, null, null, null, 'text', '下一页', null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('nextUrl', 'qichacha', '1', 'div[class=text-left m-t-lg m-b-lg]>ul>li>a[class=next]', null, null, null, 'href', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('nominalLayer', 'dldc_gx', '1', 'ceng', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '名义层', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('nominalLayer', 'dldc_ls', '1', 'ceng', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '名义层', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('operateRange', 'qichacha', '1', 'ul[class=company-base]>li', null, null, null, 'text', null, null, '', '', 'text', '经营范围', '经营范围：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('operatingPeriod', 'qichacha', '1', 'ul[class=company-base]>li', null, null, null, 'text', null, null, '', '', 'text', '营业期限', '营业期限：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('parkingInfo', 'tmsf', '1', 'div[class=buildshowin_contant ft14 colordg]>ul>li:contains(车位信息)', null, null, 'empty', 'text', null, null, '', '', '', '', '车位信息：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('parkingInfo_1', 'tmsf', '1', 'div[id=myCont5]>div:eq(5)', null, null, null, 'text', null, null, '', '', '', '', null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('pDeveloper', 'zqfgzx', '1', 'table[class=\'table table-bordered table-condensed table-hover\']>tbody>tr>td:eq(1)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '开发商', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('phone', 'qichacha', '1', 'span[class=clear m_comInfo]>small', null, null, 'a', 'text', null, null, '', '', 'text', '电话', '电话：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('preSaleCardNum', 'dldc_gx', '1', 'xkzh', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '许可证号', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('preSaleCardNum', 'dldc_ls', '1', 'xkzh', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '许可证号', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('preSaleCode', 'cqfcglj', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, null, null, 'text', '预售证号', '预售证号', null, '0', '预售证号', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('preSalePeriod', 'cqfcglj', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, null, null, 'text', '预售期限', '预售期限', null, '0', '预售期限', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('preSalePermitNo', 'zqfgzx', '1', 'table[class=\'table table-bordered table-condensed table-hover\']>tbody>tr>td:eq(4)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '预售许可证', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('presellCardName', 'nb_cnnbfdc', '1', 'table>tbody>tr:gt(0)>td:eq(1)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('presellCode', 'cqgtfw', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, '', '', 'text', '预售证号', '预售证号', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('presellId', 'nb_cnnbfdc', '1', 'table>tbody>tr:gt(0)>td:eq(1)>a', null, null, 'empty', 'onclick', 'psaleid=', '\',', null, null, null, null, null, null, '0', '预售ID', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('presellInfoUrl', 'cqgtfw', '1', 'table[class=table1 table2]>tbody>tr>td>a', null, null, 'empty', 'href', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('presellPeriod', 'cqgtfw', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, '', '', 'text', '预售期限', '预售期限', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('presellPrice', 'zqfgzx', '1', 'table[class=\'table table-bordered table-condensed table-hover\']>tbody>tr>td:eq(2)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('presellUrl', 'nb_cnnbfdc', '1', 'table>tbody>tr:gt(0)>td:eq(1)>a[class=sp_zi12c]', null, null, 'empty', 'onclick', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('presellUrl', 'tmsf', '1', 'div[id=buildnavbar]>a:contains(一房一价)', null, null, 'empty', 'href', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectCompany', 'tmsf', '1', 'div[class=buildtxtbox classones fl famwei]>p:contains(项目公司)', null, null, 'empty', 'text', null, null, '', '', '', '', '项目公司：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectCompany_1', 'tmsf', '1', 'div[class=xf_box_02]>p:contains(项目公司)', null, null, null, 'text', null, null, '', '', '', '', '项目公司：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectId', 'dldc_gx', '1', 'ysxkid', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '项目ID', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectId', 'dldc_ls', '1', 'ysxkid', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '项目ID', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectId', 'dldc_sq', '1', 'a[class=\'blue12\']', null, null, 'empty', 'href', '/fdc/D01XmxxAction.do?Control=detail&id=', '&xmbh=', null, null, null, null, null, null, '0', '项目ID', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectId', 'nb_cnnbfdc', '1', 'a[class=sp_zi12c]', null, null, 'empty', 'href', 'lpxxshow.aspx?projectid=', null, null, null, null, null, null, null, '0', '项目ID', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectId', 'zqfgzx', '1', 'table[class=\'table Roomcount table-bordered table-condensed table-hover\']>tbody>tr>td:eq(1)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '项目ID', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectName', 'cqfcglj', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, null, null, 'text', '项目名称', '项目名称', null, '0', '项目名称', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectName', 'cqgtfw', '1', 'div[class=wrap-c-m]>table>tbody>tr>td>table>tbody>tr', null, null, 'empty', 'text', null, null, '', '', 'text', '项目名称', '项目名称', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectName', 'dldc_gx', '1', 'xmmc', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '项目名称', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectName', 'dldc_ls', '1', 'xmmc', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '项目名称', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectName', 'nb_cnnbfdc', '1', 'table>tbody>tr:gt(0)>td:eq(2)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectName', 'tmsf', '1', 'div[class=lpxqtop]>div>div>span[class=buidname colordg]', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectName', 'zqfgzx', '1', 'table[class=\'table Roomcount table-bordered table-condensed table-hover\']>tbody>tr>td:eq(2)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '项目名称', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectName_1', 'tmsf', '1', 'div[id=head]>ul>li[class=a]', null, null, null, 'text', null, null, '', '', '', '', null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectUrl', 'dldc_jz', '1', 'form[name=ysxkzForm]>table>tbody>tr:gt(0)>td>a', null, null, 'empty', 'href', null, null, null, null, null, null, null, null, '0', '项目URL', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectUrl', 'dldc_sq', '1', 'a[class=\'blue12\']', null, null, 'empty', 'href', 'javascript:callNewWindow1(\'', '\',\'_blank\'', null, null, null, null, null, null, '0', '项目URL', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('projectUrl', 'nb_cnnbfdc', '1', 'td[class=sp_sck]>table>tbody>tr>td:eq(1)>a[class=sp_zi12c]', null, null, 'empty', 'href', null, null, null, null, null, null, null, null, '0', '项目Url', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('propertyCompany', 'tmsf', '1', 'div[class=buildshowin_contant ft14 colordg]>ul>li:contains(物业公司)', null, null, 'empty', 'text', null, null, '', '', '', '', '物业公司：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('propertyLife', 'tmsf', '1', 'div[class=buildshowin_contant ft14 colordg]>ul>li:contains(产权年限)', null, null, 'empty', 'text', null, null, '', '', '', '', '产权年限：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('propertyLife_1', 'tmsf', '1', 'div[id=myCont5]>div>p:contains(产权年限)', null, null, null, 'text', null, null, '', '', '', '', '产权年限：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('propertyType', 'tmsf', '1', 'div[class=buildtxtbox classones fl famwei]>ul>li:contains(物业类型)', null, null, 'empty', 'text', null, null, '', '', '', '', '物业类型：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('propertyType_1', 'tmsf', '1', 'div[class=xf_box_02]>p:contains(物业类型)', null, null, null, 'text', '物业类型：', '主力户型', '', '', '', '', null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('purpose', 'dldc_gx', '1', 'yt', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '用途', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('purpose', 'dldc_ls', '1', 'yt', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '用途', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('realEstate', 'zqfgzx', '1', 'dl[class=\'dl-horizontal buildinginfo\']>dd>font', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '楼盘', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('redecorateStatus', 'tmsf', '1', 'div[class=buildtxtbox classones fl famwei]>ul>li:contains(装修状况)', null, null, 'empty', 'text', null, null, '', '', '', '', '装修状况：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('redecorateStatus_1', 'tmsf', '1', 'div[class=xf_box_02]>p:contains(装修状况)', null, null, null, 'text', '装修状况：', null, '', '', '', '', null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('region', 'nb_cnnbfdc', '1', 'table>tbody>tr:gt(0)>td:eq(4)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('registeredCapital', 'qichacha', '1', 'ul[class=company-base]>li', null, null, null, 'text', null, null, '', '', 'text', '注册资本', '注册资本：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('roomArea', 'dldc_gx', '1', 'tnmj', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '套内面积', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('roomArea', 'dldc_ls', '1', 'tnmj', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '套内面积', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('roomId', 'dldc_gx', '1', 'fwid', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '房间ID', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('roomId', 'dldc_ls', '1', 'fwid', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '房间ID', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('roomNo', 'dldc_gx', '1', 'dh', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '房间号', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('roomNo', 'dldc_ls', '1', 'dh', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '房间号', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('salesArea', 'dldc_gx', '1', 'xsmj', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '销售面积', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('salesArea', 'dldc_ls', '1', 'xsmj', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '销售面积', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('searchDataUrl', 'qichacha', '1', 'section[id=searchlist]>table>tbody>tr>td>a', null, null, 'empty', 'href', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('sellControlUrl_1', 'tmsf', '1', 'a[id=control]', null, null, null, 'href', null, null, '', '', '', '', null, null, '0', '售控页面url', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('sid', 'tmsf', '1', 'input[id=sid]', null, null, 'empty', 'value', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('soldArea', 'zqfgzx', '1', 'table[class=\'table Roomcount table-bordered\']>tbody>tr:eq(0)>td:eq(4)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '销售面积', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('status', 'qichacha', '1', 'ul[class=company-base]>li', null, null, null, 'text', null, null, '', '', 'text', '经营状态', '经营状态：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('structure', 'dldc_gx', '1', 'jg', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '建筑结构', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('structure', 'dldc_ls', '1', 'jg', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '建筑结构', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('totalHouses', 'tmsf', '1', 'div[class=buildshowin_contant ft14 colordg]>ul>li:contains(总户数)', null, null, 'empty', 'text', null, null, '', '', '', '', '总户数：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('totalHouses_1', 'tmsf', '1', 'div[id=myCont5]>div>p:contains(户 数)', null, null, null, 'text', null, null, '', '', '', '', '总户数：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('totalLayer', 'dldc_gx', '1', 'zcs', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '楼栋总层数', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('totalLayer', 'dldc_ls', '1', 'zcs', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '楼栋总层数', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('totalOnlineSales', 'zqfgzx', '1', 'table[class=\'table Roomcount table-bordered\']>tbody>tr:eq(0)>td:eq(0)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '网上销售总套数', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('turnoverTimes', 'dldc_gx', '1', 'hscs', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '换手次数', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('turnoverTimes', 'dldc_ls', '1', 'hscs', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '换手次数', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('unitAddress', 'dldc_gx', '1', 'zl', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '楼盘地址', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('unitAddress', 'dldc_ls', '1', 'zl', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '楼盘地址', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('unitId', 'dldc_gx', '1', 'lpid', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '楼盘ID', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('unitId', 'dldc_ls', '1', 'lpid', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '楼盘ID', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('unitId', 'nb_cnnbfdc', '1', 'table>tbody>tr:gt(0)>td:eq(0)>a[class=\'e_huangse\']', null, null, null, 'onclick', 'window.open(\'housetable.aspx?qrykey=', '&projectid=', null, null, null, null, null, null, '0', '楼栋ID', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('unitId', 'zqfgzx', '1', 'table[class=\'table table-bordered table-condensed table-hover\']>tbody>tr>td:eq(0)>a', null, null, 'empty', 'href', '/index.php?s=/Property/buildview/buildid/', '.html', null, null, null, null, null, null, '0', '楼栋ID', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('unitNo', 'dldc_gx', '1', 'dh', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '销售楼号', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('unitNo', 'dldc_ls', '1', 'dh', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '销售楼号', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('unitUrl', 'nb_cnnbfdc', '1', 'table>tbody>tr:gt(0)>td:eq(0)>a[class=\'e_huangse\']', null, null, null, 'onclick', 'window.open(\'', '\',', null, null, null, null, null, null, '0', '楼栋信息Url', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('unitUrl', 'zqfgzx', '1', 'table[class=\'table table-bordered table-condensed table-hover\']>tbody>tr>td:eq(0)>a', null, null, 'empty', 'href', null, null, null, null, null, null, null, null, '0', '楼栋URL', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('website', 'qichacha', '1', 'span[class=clear m_comInfo]>small>a>label', null, null, null, 'href', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('主力户型_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(0)>tbody>tr>td>table>tbody>tr>td>span[id=Lable_Mainapirl]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '主力户型_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('交通_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(3)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Traffic]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '交通_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('交通概况_1', 'czfdc', '1', 'div[id=houseDetail0501]>table>tbody>tr>td>div>table>tbody>tr>td', null, null, 'empty', 'text', null, null, null, null, 'text', '交通概况', '交通概况：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('付款方式_1', 'czfdc', '1', 'div[id=houseDetail0501]>table>tbody>tr>td>div>table>tbody>tr>td', null, null, 'empty', 'text', null, null, null, null, 'text', '付款方式', '付款方式：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('企业名称_1', 'cq315house', '1', 'table[id=InfoListShowTb]>tbody>tr>td>div[class=info]>ul>li>span[id=Span2]', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('企业名称_2', 'cq315house', '1', 'table[id=tbDetail]>tbody:eq(1)>tr>td:eq(1)>div:eq(1)>div>div', null, null, 'empty', 'text', null, null, '', '', 'text', '企业名称', '企业名称：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('企业名称_2', 'sh_fangdi', '1', 'td[valign=top]>table[width=508]>tbody>tr:eq(2)>td:eq(1)>a', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '企业名称_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('企业报价_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(0)>tbody>tr>td>table>tbody>tr>td>span[id=Label_AveragePrice]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '企业报价_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('住宅套数_3', 'sh_fangdi', '1', 'table>tbody>tr[bgcolor!=F8EEC9]>td:eq(4)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '住宅套数_3', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('住宅面积_3', 'sh_fangdi', '1', 'table>tbody>tr[bgcolor!=F8EEC9]>td:eq(6)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '住宅面积_3', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('使用用途_3', 'cq315house', '1', 'div[id=DivInfo]>table>tbody>tr:eq(2)>td:eq(1)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('供气_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lb_Gas]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '供气_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('供水_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_WaterSupply]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '供水_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('供电_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_PowerSupply]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '供电_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('停车位_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(2)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_TCW]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '停车位_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('入住时间_1', 'czfdc', '1', 'div[id=houseDetail0501]>table>tbody>tr>td>div>table>tbody>tr>td', null, null, 'empty', 'text', null, null, null, null, 'text', '入住时间', '入住时间：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('其他_1_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(3)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Others]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '其他_1_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('其他_2_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Bs_other]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '其他_2_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('内墙_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Interior]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '内墙_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('办结时间_2', 'cq315house', '1', 'table[id=tbDetail]>tbody:eq(1)>tr>td:eq(1)>div:eq(1)>div>div:eq(4)>div', null, null, 'empty', 'text', null, null, '', '', 'text', '预售许可办结时间', '预售许可办结时间：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('包含户型_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(2)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_BHHX]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '包含户型_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('医疗_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(3)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Hospital]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '医疗_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('占地面积_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(5)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_ZDMJ]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '占地面积_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('卫生间_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Bathroom]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '卫生间_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('厨房_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Kitchen]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '厨房_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('参考价格_1', 'czfdc', '1', 'div[id=houseDetail04]>table>tbody>tr>td>table>tbody>tr:eq(0)>td:eq(2)>span', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('发证日期_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', '发证日期', '发证日期：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('可售住宅套数_2', 'cq315house', '1', 'table[id=tbDetail]>tbody:eq(1)>tr>td:eq(4)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('可售楼栋_1', 'cq315house', '1', 'table[id=InfoListShowTb]>tbody>tr>td>div[class=info]>ul>li>div[class=block]', null, null, 'empty', 'text', null, null, '', '', '', '', '可售楼栋：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('可售非住宅件数_2', 'cq315house', '1', 'table[id=tbDetail]>tbody:eq(1)>tr>td:eq(5)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('周边配套_1', 'czfdc', '1', 'div[id=houseDetail0501]>table>tbody>tr>td>div>table>tbody>tr>td', null, null, 'empty', 'text', null, null, null, null, 'text', '周边配套', '周边配套：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('售楼地址_1', 'czfdc', '1', 'div[id=houseDetail04]>table>tbody>tr>td>table>tbody>tr:eq(5)>td:eq(1)>span', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('售楼地址_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(0)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_SLDZ]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '售楼地址_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('商业_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(3)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Shop]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '商业_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('土地使用年限_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(2)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_TDSYNX]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '土地使用年限_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('土地使用证号_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', '土地使用证号', '土地使用证号：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('外墙_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_WQ]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '外墙_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('大厅_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_DT]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '大厅_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('套内面积_3', 'cq315house', '1', 'div[id=DivInfo]>table>tbody>tr:eq(1)>td:eq(1)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('安防_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Security]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '安防_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('容积率_1', 'czfdc', '1', 'div[id=houseDetail0501]>table>tbody>tr>td>div>table>tbody>tr>td', null, null, 'empty', 'text', null, null, null, null, 'text', '容积率', '容积率：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('容积率_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(2)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_RJL]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '容积率_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('座落_1', 'cq315house', '1', 'table[id=InfoListShowTb]>tbody>tr>td>div[class=info]>ul>li>span[id=Span3]', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('建筑类型_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(0)>tbody>tr>td>table>tbody>tr>td>span[id=Label_ConstructionType]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '建筑类型_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('建筑结构_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(5)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_JZJG]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '建筑结构_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('建筑结构_3', 'cq315house', '1', 'div[id=DivInfo]>table>tbody>tr:eq(4)>td:eq(3)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('建筑面积_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(5)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_JZMJ]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '建筑面积_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('建筑面积_3', 'cq315house', '1', 'div[id=DivInfo]>table>tbody>tr:eq(1)>td:eq(3)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('开发企业_1', 'szpl_gov', '1', 'table[id=\'DataList1\']>tbody>tr>td>table>tbody>tr>td:eq(3)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('开发企业_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', '开发企业', '开发企业：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('开发企业_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(6)>tbody>tr>td>table>tbody>tr>td>span[id=Label_DevName]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '开发企业_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('开发商_1', 'czfdc', '1', 'div[id=houseDetail04]>table>tbody>tr>td>table>tbody>tr:eq(4)>td:eq(1)>span', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('开盘日期_3', 'sh_fangdi', '1', 'table>tbody>tr[bgcolor!=F8EEC9]>td:eq(2)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '开盘日期_3', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('开盘时间_1', 'czfdc', '1', 'div[id=houseDetail0501]>table>tbody>tr>td>div>table>tbody>tr>td', null, null, 'empty', 'text', null, null, null, null, 'text', '开盘时间', '开盘时间：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('开盘时间_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(0)>tbody>tr>td>table>tbody>tr>td[class=sf_xq_jfsj]', null, null, 'span|div', 'text', null, null, null, null, null, null, null, null, '0', '开盘时间_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('总套数_1', 'sh_fangdi', '1', 'center>table(6)>tbody>tr[valign=middle]>td[4]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('总套数_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(2)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_ZTS]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '总套数_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('总套数_3', 'sh_fangdi', '1', 'table>tbody>tr[bgcolor!=F8EEC9]>td:eq(3)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '总套数_3', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('总套数_4', 'sh_fangdi', '1', 'table>tbody>tr[class=indextabletxt]>td:eq(4)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '总套数_4', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('总建面积_1', 'czfdc', '1', 'div[id=houseDetail0501]>table>tbody>tr>td>div>table>tbody>tr>td', null, null, 'empty', 'text', null, null, null, null, 'text', '总建面积', '总建面积：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('总面积_1', 'sh_fangdi', '1', 'center>table(6)>tbody>tr[valign=middle]>td[5]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('总面积_3', 'sh_fangdi', '1', 'table>tbody>tr[bgcolor!=F8EEC9]>td:eq(5)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '总面积_3', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('总面积_4', 'sh_fangdi', '1', 'table>tbody>tr[class=indextabletxt]>td:eq(5)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '总面积_4', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('户型_3', 'cq315house', '1', 'div[id=DivInfo]>table>tbody>tr:eq(2)>td:eq(3)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('房号_3', 'cq315house', '1', 'div[id=DivInfo]>table>tbody>tr:eq(0)>td:eq(1)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('房屋状态_3', 'cq315house', '1', 'div[id=DivInfo]>table>tbody>tr:eq(5)>td:eq(3)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('所在区_1', 'szpl_gov', '1', 'table[id=\'DataList1\']>tbody>tr>td>table>tbody>tr>td:eq(4)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('所在区县_1', 'sh_fangdi', '1', 'center>table(6)>tbody>tr[valign=middle]>td[6]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('所在区县_2', 'sh_fangdi', '1', 'td[valign=top]>table[width=508]>tbody>tr:eq(0)>td:eq(3)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '所在区县_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('所在地区_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', '所在地区', '所在地区：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('所属区县_1', 'cq315house', '1', 'table[id=InfoListShowTb]>tbody>tr>td>div[class=info]>ul>li>span[id=Span4]', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('所属区域_1', 'czfdc', '1', 'div[id=houseDetail04]>table>tbody>tr>td>table>tbody>tr:eq(2)>td:eq(1)>span', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('所属商圈_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(0)>tbody>tr>td>table>tbody>tr>td>span[id=Label_SQ]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '所属商圈_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('所属城区_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(0)>tbody>tr>td>table>tbody>tr>td>span[id=Label_CityArea]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '所属城区_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('所属板块_2', 'sh_fangdi', '1', 'td[valign=top]>table[width=508]>tbody>tr:eq(1)>td:eq(3)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '所属板块_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('所属行政区_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', '所属行政区', '所属行政区：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('批准时间_1', 'szpl_gov', '1', 'table[id=\'DataList1\']>tbody>tr>td>table>tbody>tr>td:eq(5)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('批准预售套数_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', ' 批准预售套数', ' 批准预售套数：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('批准预售面积_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', ' 批准预售面积', ' 批准预售面积：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('报价_4', 'sh_fangdi', '1', 'table>tbody>tr[class=indextabletxt]>td:eq(1)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '报价_4', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('报价可浮动幅度_4', 'sh_fangdi', '1', 'table>tbody>tr[class=indextabletxt]>td:eq(2)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '报价可浮动幅度_4', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('拟售单价_套内_3', 'cq315house', '1', 'div[id=DivInfo]>table>tbody>tr:eq(3)>td:eq(1)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('拟售单价_建面_3', 'cq315house', '1', 'div[id=DivInfo]>table>tbody>tr:eq(3)>td:eq(3)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('教育_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(3)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_School]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '教育_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('施工单位_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(6)>tbody>tr>td>table>tbody>tr>td>span[id=Label_WorkCompany]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '施工单位_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('施工编号_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', '施工编号', '施工编号：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('最大栋距_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(5)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_ZDDJ]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '最大栋距_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('最小栋距_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(5)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_ZXDJ]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '最小栋距_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('楼号_3', 'cq315house', '1', 'div[id=DivInfo]>table>tbody>tr:eq(0)>td:eq(3)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('楼栋_2', 'cq315house', '1', 'table[id=tbDetail]>tbody:eq(1)>tr>td:eq(3)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('楼栋信息url_4', 'sh_fangdi', '1', 'table>tbody>tr[class=indextabletxt]>td:eq(0)>a', null, null, 'empty', 'href', null, null, null, null, null, null, null, null, '0', '楼栋信息url_4', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('楼栋名称_4', 'sh_fangdi', '1', 'table>tbody>tr[class=indextabletxt]>td:eq(0)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '楼栋名称_4', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('楼盘位置_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(0)>tbody>tr>td>table>tbody>tr>td>span[id=Label_ProjectAdress]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '楼盘位置_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('楼盘名称_2', 'cq315house', '1', 'table[id=tbDetail]>tbody:eq(1)>tr>td:eq(2)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('楼盘地址_1', 'czfdc', '1', 'div[id=houseDetail04]>table>tbody>tr>td>table>tbody>tr:eq(3)>td:eq(1)>span', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('消防_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_firefighting]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '消防_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('物业公司_1', 'czfdc', '1', 'div[id=houseDetail0501]>table>tbody>tr>td>div>table>tbody>tr>td', null, null, 'empty', 'text', null, null, null, null, 'text', '物业公司', '物业公司：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('物业公司_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(6)>tbody>tr>td>table>tbody>tr>td>span[id=Label_PropertyCompany]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '物业公司_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('物业类别_1', 'czfdc', '1', 'div[id=houseDetail04]>table>tbody>tr>td>table>tbody>tr:eq(1)>td:eq(1)>span', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('物业类型_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(0)>tbody>tr>td>table>tbody>tr>td>span[id=Label_Propertytypename]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '物业类型_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('物业费_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(2)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_WYF]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '物业费_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('状态_1', 'sh_fangdi', '1', 'center>table(6)>tbody>tr[valign=middle]>td[1]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('环线位置_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(2)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_HXWZ]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '环线位置_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('现房期房_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(2)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_XFQF]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '现房期房_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('电梯_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_ElevatorType]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '电梯_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('签约情况_3', 'cq315house', '1', 'div[id=DivInfo]>table>tbody>tr:eq(5)>td:eq(1)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('累计住宅合同均价_2', 'sh_fangdi', '1', 'div[id=div2]>table>tbody>tr:eq(0)>td:eq(6)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '累计住宅合同均价_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('累计住宅合同撤销均价_2', 'sh_fangdi', '1', 'div[id=div2]>table>tbody>tr:eq(2)>td:eq(6)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '累计住宅合同撤销均价_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('累计合同均价_2', 'sh_fangdi', '1', 'div[id=div2]>table>tbody>tr:eq(0)>td:eq(2)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '累计合同均价_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('累计合同撤销均价_2', 'sh_fangdi', '1', 'div[id=div2]>table>tbody>tr:eq(2)>td:eq(2)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '累计合同撤销均价_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('经度_1', 'czfdc', '1', 'input[id=Longitude]', null, null, 'empty', 'value', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('维度_1', 'czfdc', '1', 'input[id=latitude]', null, null, 'empty', 'value', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('绿化率_1', 'czfdc', '1', 'div[id=houseDetail0501]>table>tbody>tr>td>div>table>tbody>tr>td', null, null, 'empty', 'text', null, null, null, null, 'text', '绿化率', '绿化率：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('绿化率_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(2)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_LHL]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '绿化率_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('编号_3', 'sh_fangdi', '1', 'table>tbody>tr[bgcolor!=F8EEC9]>td:eq(0)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '编号_3', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('联系电话_1', 'czfdc', '1', 'div[id=houseDetail04]>table>tbody>tr>td>table>tbody>tr:eq(6)>td>table>tbody>tr>td>div>table>tbody>tr>td>div', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('营销策划_1', 'czfdc', '1', 'div[id=houseDetail0501]>table>tbody>tr>td>div>table>tbody>tr>td', null, null, 'empty', 'text', null, null, null, null, 'text', '营销/策划', '营销/策划：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('装修状况_1', 'czfdc', '1', 'div[id=houseDetail0501]>table>tbody>tr>td>div>table>tbody>tr>td', null, null, 'empty', 'text', null, null, null, null, 'text', '装修状况', '装修状况：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('装修状况_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(0)>tbody>tr>td>table>tbody>tr>td>span[id=Label_Dekoration]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '装修状况_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('购物_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(3)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_GW]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '购物_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('轨道交通_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(2)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_GDJT]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '轨道交通_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('通讯_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Communications]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '通讯_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('采暖_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Heating]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '采暖_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('银行_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(3)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Bank', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '银行_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('销售代理公司_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', '销售代理公司', '销售代理公司：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('销售信息url_3', 'sh_fangdi', '1', 'table>tbody>tr[bgcolor!=F8EEC9]>td:eq(1)>a', null, null, 'empty', 'href', null, null, null, null, null, null, null, null, '0', '销售信息url_3', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('销售状态_3', 'sh_fangdi', '1', 'table>tbody>tr[bgcolor!=F8EEC9]>td:eq(7)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '销售状态_3', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('销售状态_4', 'sh_fangdi', '1', 'table>tbody>tr[class=indextabletxt]>td:eq(6)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '销售状态_4', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('门窗_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(4)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_MC]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '门窗_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目信息url_1', 'xianfang99', '1', 'div[id=floatdiv]>div>div>ul>li:eq(1)>a', null, null, 'empty', 'href', null, null, null, null, null, null, null, null, '0', '项目信息url_1', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目名称_1', 'cq315house', '1', 'table[id=InfoListShowTb]>tbody>tr>td>div[class=info]>ul>li>div[class=project]>a', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目名称_1', 'czfdc', '1', 'div[id=houseDetail04]>table>tbody>tr>td>span', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目名称_1', 'sh_fangdi', '1', 'center>table(6)>tbody>tr[valign=middle]>td[2]>a', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目名称_1', 'szpl_gov', '1', 'table[id=\'DataList1\']>tbody>tr>td>table>tbody>tr>td:eq(2)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目名称_2', 'cq315house', '1', 'table[id=tbDetail]>tbody:eq(1)>tr>td:eq(1)>div:eq(1)>div>h4', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目名称_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', '项目名称', '项目名称：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目名称_2', 'sh_fangdi', '1', 'td[valign=top]>table[width=508]>tbody>tr:eq(0)>td:eq(1)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '项目名称_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目名称_2', 'xianfang99', '1', 'div[id=bc_body]>div>div>span[class=sf_xq_xmmc]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '项目名称_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目名称_url_1', 'szpl_gov', '1', 'table[id=\'DataList1\']>tbody>tr>td>table>tbody>tr>td:eq(2)>a', null, null, 'empty', 'href', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目地址_1', 'sh_fangdi', '1', 'center>table(6)>tbody>tr[valign=middle]>td[3]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目地址_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', '项目地址', '项目地址：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目地址_2', 'sh_fangdi', '1', 'td[valign=top]>table[width=508]>tbody>tr:eq(1)>td:eq(1)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '项目地址_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目所在地址_2', 'cq315house', '1', 'table[id=tbDetail]>tbody:eq(1)>tr>td:eq(1)>div:eq(1)>div>div', null, null, 'empty', 'text', null, null, '', '', 'text', '项目地址', '项目地址：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目简介_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(1)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_Introduction]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '项目简介_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('项目详细_url_1', 'sh_fangdi', '1', 'center>table(6)>tbody>tr[valign=middle]>td[2]>a', null, null, 'empty', 'href', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售件数_2', 'cq315house', '1', 'table[id=tbDetail]>tbody:eq(1)>tr>td:eq(1)>div:eq(1)>div>div:eq(4)>div', null, null, 'empty', 'text', null, null, '', '', 'text', '预售件数', '预售件数：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售信息url_2', 'sh_fangdi', '1', 'iframe[id=SUList]', null, null, 'empty', 'src', null, null, null, null, null, null, null, null, '0', '预售信息url_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售建筑面积_2', 'cq315house', '1', 'table[id=tbDetail]>tbody:eq(1)>tr>td:eq(1)>div:eq(1)>div>div:eq(4)>div', null, null, 'empty', 'text', null, null, '', '', 'text', '预售建筑面积', '预售建筑面积：', null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售批准机关_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', '预售批准机关', '预售批准机关：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售许可证_1', 'czfdc', '1', 'div[id=houseDetail0501]>table>tbody>tr>td>div>table>tbody>tr>td', null, null, 'empty', 'text', null, null, null, null, 'text', '预售许可证', '预售许可证：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售许可证_3', 'cq315house', '1', 'div[id=DivInfo]>table>tbody>tr:eq(4)>td:eq(1)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售许可证号_1', 'cq315house', '1', 'table[id=InfoListShowTb]>tbody>tr>td>div[class=info]>ul>li>span[id=Span5]', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售许可证号_2', 'czfdc', '1', 'table[class=a_date_search_mid_04]>tbody>tr>td', null, null, 'span', 'text', null, null, null, null, 'text', '预售许可证号', '预售许可证号：', null, '0', null, '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售许可证房产证号_2', 'cq315house', '1', 'table[id=tbDetail]>tbody:eq(1)>tr>td:eq(1)>div:eq(0)', null, null, 'empty', 'text', null, null, '', '', '', '', null, null, '0', '0', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售许可证房地产权证_3', 'sh_fangdi', '1', 'table>tbody>tr[bgcolor!=F8EEC9]>td:eq(1)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '预售许可证房地产权证_3', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售证号_1', 'szpl_gov', '1', 'table[id=\'DataList1\']>tbody>tr>td>table>tbody>tr>td:eq(1)', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售证号_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(2)>tbody>tr>td>table>tbody>tr>td>span[id=Label_SallPreDocuments]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '预售证号_2', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('预售证号_url_1', 'szpl_gov', '1', 'table[id=\'DataList1\']>tbody>tr>td>table>tbody>tr>td:eq(1)>a', null, null, 'empty', 'href', null, null, null, null, null, null, null, null, '0', '', '0');
INSERT INTO `ex_crawler_platform_extract_path` VALUES ('餐饮_2', 'xianfang99', '1', 'div[class=sf_cat ztys2]>table:eq(3)>tbody>tr>td>table>tbody>tr>td>span[id=lbl_CY]', null, null, 'empty', 'text', null, null, null, null, null, null, null, null, '0', '餐饮_2', '0');
